SELECT *
FROM pizza_sales

--FINDING THE TOTAL REVENUE OF PIZZA SALES

SELECT SUM(total_price) AS Total_Revenue
FROM pizza_sales

--FINDING AVERAGE ORDER VALUE
SELECT SUM(total_price)/COUNT(DISTINCT order_id) AS AVERAGE_ORDER_VALUE
FROM pizza_sales

--FINDING TOTAL PIZZAS SOLD
SELECT SUM(quantity) as TOTAL_PIZZAS_SOLD
FROM pizza_sales

--FINDING TOTAL ORDER 
SELECT COUNT(DISTINCT order_id) AS TOTAL_ORDER
FROM pizza_sales

--FINDING AVERAGE PIZZAS SOLD PER ORDER

SELECT CAST(CAST(SUM(quantity) AS DECIMAL(10,2))/
CAST(COUNT(DISTINCT order_id) AS DECIMAL(10,2)) AS DECIMAL(10,2)) as AVERAGE_PIZZAS_SOLD_PER_ORDER
FROM pizza_sales

--DAILY TREND FOR TOTAL ORDERS

SELECT DATENAME(DW, order_date) as ORDER_DAY,
COUNT(DISTINCT order_id) AS TOTAL_ORDERS
FROM pizza_sales
GROUP BY DATENAME(DW, order_date) 


--MONTHLY TREND FOR TOTAL ORDERS

SELECT DATENAME(MONTH, order_date) AS ORDER_MONTH,
COUNT(DISTINCT order_date) AS TOTAL_ORDERS
from pizza_sales
GROUP BY DATENAME(MONTH, order_date) 
ORDER BY  TOTAL_ORDERS DESC

--PERCENTAGE OF SALES BY PIZZA CATEGORY

SELECT pizza_category,SUM(total_price)AS TOTAL_SALES,
SUM(total_price)*100/(SELECT SUM(total_price) FROM pizza_sales WHERE MONTH(order_date)=1) AS PCT
FROM pizza_sales
WHERE MONTH(order_date)=1
GROUP BY pizza_category

--PERCENTAGE OF SALES BY PIZZA SIZE

SELECT pizza_size,SUM(total_price) AS TOTAL_SALES,
SUM(total_price)*100/(SELECT SUM(total_price) FROM pizza_sales WHERE DATEPART(QUARTER, order_date)=1) AS PCT
FROM pizza_sales
WHERE DATEPART(QUARTER, order_date)=1
GROUP BY pizza_size
ORDER BY PCT DESC

--TOP 5 BEST SELLERS BY REVENUE, TOTAL QUANTITY AND TOTAL ORDERS

SELECT TOP 5 pizza_name , SUM(total_price) AS TOTAL_REVENUE
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_REVENUE DESC

SELECT TOP 5 pizza_name , SUM(quantity) AS TOTAL_QUANTITY
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_QUANTITY DESC


SELECT TOP 5 pizza_name , COUNT(DISTINCT order_id) AS TOTAL_ORDERS
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_ORDERS DESC

--BOTTOM 5 BEST SELLERS BY REVENUE, TOTAL QUANTITY AND TOTAL ORDERS

SELECT TOP 5 pizza_name , SUM(total_price) AS TOTAL_REVENUE
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_REVENUE ASC

SELECT TOP 5 pizza_name , SUM(quantity) AS TOTAL_QUANTITY
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_QUANTITY ASC

SELECT TOP 5 pizza_name , COUNT(DISTINCT order_id) AS TOTAL_ORDERS
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_ORDERS ASC


